pipeline {
    agent any
    tools { go '1.23.1' 
            dockerTool "Docker"}

// Need to have Docker and GO plugins installed on Jenkins
    stages {

        stage('Unit Tests') {
            steps {
                script {
                    // Setting up Go environment
                    //def goVersion = ">=1.23.0"
                    sh "go version"
                    // Running unit tests
                    sh '''
                    git clone https://https://github.com/Zachdehooge/Go-Security-Scanner
                    cd Go-Security-Scanner
                    pwd
                    echo "Running unit tests..."
                    go test main_test.go
                    echo "Unit Tests Complete"
                    '''
                }
            }
        }

        stage('Static Testing'){
            steps{
                script{

                }
            }
        }

        stage("Dynamic Testing"){
            steps{
                script{
                    
                }
            }
        }
    } 
    post {
        always {
            cleanWs()
        }
    }
}
